name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run doc tests 
      run: cargo --verbose test --doc --
    - name: Run documentation 
      run: cargo  --verbose doc
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run Clippy
      run: cargo clippy -- -Dwarnings 
    - name: Run tests
      run: cargo test


