name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run doc tests 
      run: cargo +nightly --verbose test --doc --
    - name: Run documentation 
      run: cargo +nightly  --verbose doc

